services:
  minecraft-server:
    image: itzg/minecraft-server
    container_name: minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"  # Accepts EULA Minecraft
      MEMORY: "2G"  # RAM
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped